name: 🕶️

on:
  push:
    branches:
      - "**"
  pull_request:
    branches:
      - main

jobs:
  style-checks:
    name: Run style checks
    runs-on: ubuntu-latest
    container: bempp/cl-dev-env-with-dolfinx-numba
    steps:
      - uses: actions/checkout@v4
      - run: pip3 install -e .[style]
      - run: |
          python3 -m ruff check .
          python3 -m ruff format --check .
        name: Run ruff checks
      - run: python3 -m isort --check .
        name: Run isort check
      - run: python3 -m mypy .
        name: Run mypy checks
